site:
  title: IvorySQL Document Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.ivorysql.org
  start_page: ivorysql-doc::v3.3/welcome.adoc
content:
  sources:
  - url: git@github.com:IvorySQL/ivorysql_docs.git
    branches: [v3.*, v2.*,v1.*,developer]
    start_paths:
    - EN
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
output:
  dir: ../docs/en
ui:
  bundle:
    url: https://github.com/IvorySQL/ivory-doc-builder/raw/main/entemplates.zip
    snapshot: true
runtime:
  fetch: true
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [en]
  - '@antora/pdf-extension'
